### ISSUE TITLE
Suggestions for additional commands

### ISSUE THREAD

**Issue by DannyBen** [DannyBen/victor-cli#3]
To make victor-cli more useful, maybe we should consider these:

- [ ] Add `victor init [RUBY_FILE]` command, that will save a sample - this template should be special - without the `svg.save` and maybe without the initial `Victor::SVG.new`.
- [x] Add `victor to-svg RUBY_FILE [SVG_FILE]` command that will run and save/generate the Ruby file.
- [x] Rename the `generate` command to something like `to-ruby` to avoid the "what are we generating" confusion.
- [ ] Maybe add `victor icodi STRING [SVG_FILE]` that generates [icodi](https://github.com/dannyben/icodi) icon?

@gingermusketeer thoughts?

**Comment by gingermusketeer** [comment]
Changing `generate` to `to-ruby` sounds good, especially if `to-svg` is implemented.

For the `to-svg` command it might be nice to have a watch mode so that any changes to the file trigger the SVG to be regenerated. I have been using a SVG preview plugin for VScode but I had to manually run the command again to see the changes.

The other thing we could do with the `to-ruby` command is allow a flag to convert into a symbol rather than a full SVG. This is handy when embedding an SVG inside one another.

**Comment by DannyBen** [comment]
I have an idea on how I think `to-svg` should work. The important thing I want to solve here, is that there is no point in that source Ruby file, to just be classic Ruby file, since if it is, there is no point in running it with `victor` instead of running it with `ruby`.

So - I want to set some tiny minimal conventions that will make it look like DSL.

I intend to try something later today, and I will assume you wish to be involved until you tell me otherwise.

**Comment by DannyBen** [comment]
Closing this, since we added most, and I created #10 to cover next logical command.
